# Generated by Django 5.2.12 on 2026-03-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neondatabase',
            name='service_id',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='neondatabase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='neondatabase',
            unique_together={('organization', 'service_id')},
        ),
    ]
