# Generated by Django 5.2.12 on 2026-03-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_neondatabase_service_id_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neondatabase',
            name='zcp_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='projects.project'),
        ),
    ]
