# Generated by Django 5.2.12 on 2026-03-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'name')},
        ),
    ]
