# Generated by Django 5.2.12 on 2026-03-13 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, max_length=255)),
                ('service_urls', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('deploying', 'Deploying'), ('ready', 'Ready'), ('error', 'Error')], default='deploying', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('temporal_workflow_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_app', to='organizations.organization')),
            ],
        ),
    ]
