# Generated by Django 5.2.12 on 2026-03-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedapp',
            name='zcp_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployed_apps', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='deployedapp',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_apps', to='organizations.organization'),
        ),
    ]
